name: Publish Docker image
env:
  DOCKER_BUILDKIT: 1

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: latest
        required: true

  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  publish_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get latest Playwright version
        id: get_version
        run: |
          if [ "${{ github.event.inputs.version }}" = "latest" ]; then
            LATEST_VERSION=$(curl -s https://mcr.microsoft.com/v2/playwright/tags/list | jq -r '.tags[]' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
            echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          else
            echo "LATEST_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi

      - name: Download Docker image from public registry
        run: docker pull mcr.microsoft.com/playwright:${{ env.LATEST_VERSION }}

      - name: Tag Docker image
        run: |
          docker tag mcr.microsoft.com/playwright:${{ env.LATEST_VERSION }} dipjyotimetia/playwright:${{ env.LATEST_VERSION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload Docker image to private registry
        run: |
          docker push dipjyotimetia/playwright:${{ env.LATEST_VERSION }}
