name: Publish Docker image
env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - main


jobs:
  publish_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download Docker image from public registry
        run: docker pull mcr.microsoft.com/playwright:latest  

      - name: Tag Docker image
        run: docker tag mcr.microsoft.com/playwright:latest dipjyotimetia/playwright:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload Docker image to private registry
        run: docker push dipjyotimetia/playwright:latest