name: Publish Docker image
env:
  DOCKER_BUILDKIT: 1

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.38.0
        required: true

jobs:
  publish_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download Docker image from public registry
        run: docker pull mcr.microsoft.com/playwright:${{ github.event.inputs.version }}  

      - name: Tag Docker image
        run: |
          docker tag mcr.microsoft.com/playwright:${{ github.event.inputs.version }} dipjyotimetia/playwright:${{ github.event.inputs.version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload Docker image to private registry
        run: |
          docker push dipjyotimetia/playwright:${{ github.event.inputs.version }}